default: hw8-ChristianHansen-0 hw8-ChristianHansen-1 hw8-ChristianHansen-2 hw8-ChristianHansen-3

hw8-ChristianHansen-0.o: hw8-ChristianHansen-0.c
	gcc -c hw8-ChristianHansen-0.c -o hw8-ChristianHansen-0.o

hw8-ChristianHansen-0: hw8-ChristianHansen-0.o
	gcc hw8-ChristianHansen-0.o -o hw8-ChristianHansen-0

hw8-ChristianHansen-1.o: hw8-ChristianHansen-1.c
	gcc -c hw8-ChristianHansen-1.c -o hw8-ChristianHansen-1.o

hw8-ChristianHansen-1: hw8-ChristianHansen-1.o
	gcc hw8-ChristianHansen-1.o -o hw8-ChristianHansen-1

hw8-ChristianHansen-2.o: hw8-ChristianHansen-2.c
	gcc -c hw8-ChristianHansen-2.c -o hw8-ChristianHansen-2.o

hw8-ChristianHansen-2: hw8-ChristianHansen-2.o
	gcc hw8-ChristianHansen-2.o -o hw8-ChristianHansen-2

hw8-ChristianHansen-3.o: hw8-ChristianHansen-3.c
	gcc -c hw8-ChristianHansen-3.c -o hw8-ChristianHansen-3.o

hw8-ChristianHansen-3: hw8-ChristianHansen-3.o
	gcc hw8-ChristianHansen-3.o -o hw8-ChristianHansen-3

clean:
	-rm -f hw8-ChristianHansen-0.o
	-rm -f hw8-ChristianHansen-0
	-rm -f hw8-ChristianHansen-1.o
	-rm -f hw8-ChristianHansen-1
	-rm -f hw8-ChristianHansen-2.o
	-rm -f hw8-ChristianHansen-2
	-rm -f hw8-ChristianHansen-3.o
	-rm -f hw8-ChristianHansen-3
	-rm -f shared1.dat
	-rm -f shared2.dat
	-rm -f temp1.data
	-rm -f temp2.data
	-rm -f temp3.data
